#[derive(serde::Deserialize)]
pub struct ZmiArcher {
    #[serde(rename(deserialize = "VEREINNR"))]
    pub vereinnr: u64,
    #[serde(rename(deserialize = "VEREINNAME"))]
    pub vereinname: String,
    #[serde(rename(deserialize = "PERSONID"))]
    pub personid: u64,
    #[serde(rename(deserialize = "MITGLIEDSCHAFTID"))]
    pub mitgliedschaftid: u64,
    #[serde(rename(deserialize = "NAMEN"))]
    pub namen: String,
    #[serde(rename(deserialize = "VORNAME"))]
    pub vorname: String,
    #[serde(rename(deserialize = "GEBURTSDATUM"))]
    pub geburtsdatum: String,
    #[serde(rename(deserialize = "TITEL"))]
    pub titel: String,
    #[serde(rename(deserialize = "GESCHLECHT"))]
    pub geschlecht: String,
    #[serde(rename(deserialize = "STRASSE"))]
    pub strasse: String,
    #[serde(rename(deserialize = "PLZ"))]
    pub plz: String,
    #[serde(rename(deserialize = "ORT"))]
    pub ort: String,
    #[serde(rename(deserialize = "LANDID"))]
    pub landid: u64,
    #[serde(rename(deserialize = "LAND"))]
    pub land: String,
    #[serde(rename(deserialize = "EINTRITTVEREIN"))]
    pub eintrittverein: String,
    #[serde(rename(deserialize = "AUSTRITTVEREIN"))]
    pub austrittverein: String,
    #[serde(rename(deserialize = "ALTER"))]
    pub alter: u16,
    #[serde(rename(deserialize = "ZAHLUNGSART"))]
    pub zahlungsart: String,
    #[serde(rename(deserialize = "EINTRITTBSSB"))]
    pub eintrittbssb: String,
    #[serde(rename(deserialize = "EINTRITTDSB"))]
    pub eintrittdsb: String,
    #[serde(rename(deserialize = "ERSTVEREINNR"))]
    pub erstvereinnr: u64,
    #[serde(rename(deserialize = "ERSTVEREIN"))]
    pub erstverein: String,
    #[serde(rename(deserialize = "PASSNUMMER"))]
    pub passnummer: i64,
    #[serde(rename(deserialize = "MITGLIEDSJAHREVEREIN"))]
    pub mitgliedsjahreverein: u16,
    #[serde(rename(deserialize = "MITGLIEDSJAHREBSSB"))]
    pub mitgliedsjahrebssb: u16,
    #[serde(rename(deserialize = "VERSTORBENAM"))]
    pub verstorbenam: String,
    #[serde(rename(deserialize = "SPORTKLASSE"))]
    pub sportklasse: String,
    #[serde(rename(deserialize = "ALTERSGRUPPE"))]
    pub altersgruppe: String,
    #[serde(rename(deserialize = "INTERESSEN"))]
    pub interessen: String,
    #[serde(rename(deserialize = "VEREINIDENTNR"))]
    pub vereinidentnr: String,
    #[serde(rename(deserialize = "LAND_CODE2"))]
    pub land_code2: String,
    #[serde(rename(deserialize = "LAND_CODE3"))]
    pub land_code3: String,
    #[serde(rename(deserialize = "STAATSANGEHID"))]
    pub staatsangehid: String,
    #[serde(rename(deserialize = "STAATSANGEHOERIGKEIT"))]
    pub staatsangehoerigkeit: String,
    #[serde(rename(deserialize = "STAATSANGEH_CODE2"))]
    pub staatsangeh_code2: String,
    #[serde(rename(deserialize = "STAATSANGEH_CODE3"))]
    pub staatsangeh_code3: String,
    #[serde(rename(deserialize = "INTERESSENLISTE"))]
    pub interessenliste: String,
    #[serde(rename(deserialize = "MITGLIEDSNR1"))]
    pub mitgliedsnr1: String,
    #[serde(rename(deserialize = "MITGLIEDSNR2"))]
    pub mitgliedsnr2: String,
    #[serde(rename(deserialize = "MITGLIEDSNR3"))]
    pub mitgliedsnr3: String,
    #[serde(rename(deserialize = "MITGLIEDSNR4"))]
    pub mitgliedsnr4: String,
    #[serde(rename(deserialize = "Telefon"))]
    pub telefon: String,
    #[serde(rename(deserialize = "Mobil"))]
    pub mobil: String,
    #[serde(rename(deserialize = "Fax"))]
    pub fax: String,
    #[serde(rename(deserialize = "Mail"))]
    pub mail: String,
}
